let data = [
    {"pergunta": "Qual é a data do Natal?", "resposta": "25 de dezembro."},
    {"pergunta": "Em qual mês celebramos o Natal?", "resposta": "Dezembro."},
    {"pergunta": "Quem é o personagem principal do Natal?", "resposta": "Papai Noel."},
    {"pergunta": "Qual é o nome da rena do nariz vermelho?", "resposta": "Rudolph."},
    {"pergunta": "O que as pessoas costumam fazer na véspera de Natal?", "resposta": "Trocar presentes e compartilhar refeições em família."},
    {"pergunta": "Qual é a cor tradicional do Papai Noel?", "resposta": "Vermelho e branco."},
    {"pergunta": "Quem escreveu a música 'Noite Feliz'?", "resposta": "Franz Xaver Gruber e Joseph Mohr."},
    {"pergunta": "O que as crianças costumam deixar para o Papai Noel?", "resposta": "Leite e biscoitos."},
    {"pergunta": "Qual é o significado da palavra 'Natal'?", "resposta": "Nascimento."},
    {"pergunta": "Quem são os ajudantes do Papai Noel?", "resposta": "Duendes."},
    {"pergunta": "Qual é o símbolo do Natal que as pessoas penduram nas portas?", "resposta": "Guirlanda."},
    {"pergunta": "O que as pessoas costumam comer no jantar de Natal?", "resposta": "Peru, tender, bacalhau, entre outros pratos tradicionais."},
    {"pergunta": "Em que país a tradição de colocar presentes em meias começou?", "resposta": "Holanda."},
    {"pergunta": "Qual é o nome do lugar onde Jesus nasceu?", "resposta": "Belém."},
    {"pergunta": "O que é o Advento?", "resposta": "O período de quatro semanas antes do Natal."},
    {"pergunta": "Quem é conhecido como o Grinch?", "resposta": "Um personagem verde que odeia o Natal, da história do Dr. Seuss."},
    {"pergunta": "O que as pessoas costumam enfeitar durante o Natal?", "resposta": "Árvores de Natal, casas e ruas."},
    {"pergunta": "Qual é o nome da estrela que os Reis Magos seguiram?", "resposta": "Estrela de Belém."},
    {"pergunta": "O que representa a árvore de Natal?", "resposta": "Vida e renovação."},
    {"pergunta": "Quem é o 'bom velhinho' do Natal?", "resposta": "Papai Noel."},
    {"pergunta": "Qual é o animal que puxa o trenó do Papai Noel?", "resposta": "Ren..."},
    {"pergunta": "O que é o Calendário do Advento?", "resposta": "Um calendário com janelinhas que são abertas a cada dia de dezembro, geralmente com chocolates ou pequenos presentes."},
    {"pergunta": "Quem é conhecido como o 'Pai Natal' em Portugal?", "resposta": "Pai Natal."},
    {"pergunta": "Qual é o nome do boneco de neve famoso nas histórias de Natal?", "resposta": "Frosty."},
    {"pergunta": "O que significa 'Feliz Natal' em outras línguas?", "resposta": "Joyeux Noël (francês), Feliz Navidad (espanhol), Buon Natale (italiano), entre outros."},
    {"pergunta": "Quem é o autor do conto 'Um Conto de Natal'?", "resposta": "Charles Dickens."},
    {"pergunta": "O que as pessoas costumam fazer no Dia de Natal?", "resposta": "Celebrar com a família, abrir presentes e desfrutar de uma refeição festiva."},
    {"pergunta": "Qual é o nome do vilão em 'Esqueceram de Mim', um filme natalino?", "resposta": "Harry e Marv (Os Bandidos Molhados)."},
    {"pergunta": "O que as pessoas penduram nas lareiras durante o Natal?", "resposta": "Meias."},
    {"pergunta": "Qual é a importância do presépio nas decorações de Natal?", "resposta": "Representa o nascimento de Jesus."},
    {"pergunta": "Quem é conhecido como o 'Bom Velhinho' nos Estados Unidos?", "resposta": "Santa Claus."},
    {"pergunta": "O que os Duendes de Papai Noel fazem na tradição natalina?", "resposta": "Ajudam a fazer brinquedos para o Natal."},
    {"pergunta": "Qual é o nome do filme em que um menino pede um rifle de ar no Natal?", "resposta": "A Christmas Story (História de um Natal)."},
    {"pergunta": "O que as pessoas costumam fazer durante a temporada de Advento?", "resposta": "Refletir, rezar e se preparar para o Natal."},
    {"pergunta": "Quem são os três personagens principais do ballet 'O Quebra-Nozes'?", "resposta": "Clara, Quebra-Nozes e o Rei dos Ratos."},
    {"pergunta": "Qual é o nome da família no filme 'Férias Frustradas de Natal'?", "resposta": "Griswold."},
    {"pergunta": "O que as pessoas costumam colocar no topo da árvore de Natal?", "resposta": "Estrela ou anjo."},
    {"pergunta": "Quem é conhecido como o 'Krampus' em algumas tradições natalinas?", "resposta": "Uma figura mitológica que pune crianças travessas."},
    {"pergunta": "Qual é o nome do animal que aparece no poema 'A Visit from St. Nicholas'?", "resposta": "Renas do Papai Noel."},
    {"pergunta": "O que é o Dia de São Estêvão, celebrado logo após o Natal?", "resposta": "Um feriado religioso."},
    {"pergunta": "Quem são os 'Anjos da Árvore' na tradição natalina?", "resposta": "Enfeites em forma de anjos."},
    {"pergunta": "Qual é o significado das cores verde e vermelho nas decorações de Natal?", "resposta": "Verde representa vida, e vermelho simboliza o sangue de Jesus."},
    {"pergunta": "O que as pessoas costumam fazer durante a Noite de Natal?", "resposta": "Participar de uma ceia especial, trocar presentes e celebrar em família."},
    {"pergunta": "Qual é o nome do trenó mágico do Papai Noel?", "resposta": "Trenó puxado por renas."},
    {"pergunta": "O que representa a vela no Advento?", "resposta": "Cada vela simboliza uma semana antes do Natal."},
    {"pergunta": "Quem é o protagonista do filme 'Polar Express'?", "resposta": "O Garoto."},
    {"pergunta": "O que significa a tradição de trocar presentes no Natal?", "resposta": "Simboliza a troca de afeto e alegria."},
    {"pergunta": "Quem são os Reis Magos e qual é sua importância no Natal?", "resposta": "Melchior, Gaspar e Baltazar; trouxeram presentes para o Menino Jesus."},
    {"pergunta": "Qual é o significado da estrela no topo da árvore de Natal?", "resposta": "Representa a Estrela de Belém, que guiou os Magos até o local do nascimento de Jesus."},
  
    {"pergunta": "Qual é o nome do trenó do Papai Noel?", "resposta": "Trenó mágico."},
    {"pergunta": "O que as pessoas costumam fazer durante a época de Natal?", "resposta": "Trocar presentes, decorar a casa e passar tempo com a família."},
    {"pergunta": "Quem é conhecido como o 'Homem das Neves'?", "resposta": "Yeti ou Abominável Homem das Neves."},
    {"pergunta": "O que é a 'Trégua de Natal'?", "resposta": "Um episódio em que soldados pararam de lutar temporariamente durante a Primeira Guerra Mundial."},
    {"pergunta": "Qual é o significado da palavra 'Yule'?", "resposta": "Um termo associado a festividades de inverno."},
    {"pergunta": "O que é o 'Dia de São Estêvão'?", "resposta": "Celebrado em 26 de dezembro."},
    {"pergunta": "Quem é conhecido como o 'Papai Noel' em outros países?", "resposta": "Santa Claus, Kris Kringle, Pai Natal."},
    {"pergunta": "O que são os 'Christmas Markets'?", "resposta": "Feiras de Natal ao ar livre, com produtos artesanais e comidas típicas."},
    {"pergunta": "Qual é o nome do Grinch em português?", "resposta": "O Grinch."},
    {"pergunta": "O que é o 'Dia de Boxe'?", "resposta": "Celebrado no dia seguinte ao Natal, principalmente no Reino Unido e Canadá."},
    {"pergunta": "Quem são os personagens principais do filme 'Esqueceram de Mim 2'?", "resposta": "Kevin McCallister e Marv Murchins."},
    {"pergunta": "O que é o 'Festival de Luzes de Natal'?", "resposta": "Eventos em que cidades decoram prédios e ruas com luzes temáticas."},
    {"pergunta": "Qual é o nome da árvore de Natal tradicional?", "resposta": "Árvore de Natal."},
    {"pergunta": "O que significa o termo 'White Christmas'?", "resposta": "Natal com neve, referência à canção famosa."},
    {"pergunta": "Quem é conhecido como 'O Homem de Gengibre'?", "resposta": "Personagem de contos e filmes de Natal."},
    {"pergunta": "O que é o 'Calendário do Advento'?", "resposta": "Um calendário com janelinhas que são abertas a cada dia de dezembro."},
    {"pergunta": "Qual é o nome do amigo de Rudolph, a rena?", "resposta": "Hermey, o elfo dentista."},
    {"pergunta": "O que são os 'Three Wise Men'?", "resposta": "Os Três Reis Magos."},
    {"pergunta": "Quem é conhecido como o 'Papai Noel Verde'?", "resposta": "O Grinch."},
    {"pergunta": "O que é o 'Elf Bowling'?", "resposta": "Um jogo de computador temático de Natal."},
    {"pergunta": "Quem é a 'Rainha do Gelo'?", "resposta": "Personagem de contos natalinos e do filme 'O Expresso Polar'."},
    {"pergunta": "O que é o 'Dia de São Nicolau'?", "resposta": "Celebrado em 6 de dezembro, com a entrega de pequenos presentes."},
    {"pergunta": "Quem é conhecido como 'O Homem do Saco'?", "resposta": "Personagem folclórico que leva crianças travessas embora."},
    {"pergunta": "O que é o 'Glogg'?", "resposta": "Uma bebida quente de Natal, comumente feita com vinho, especiarias e frutas."},
    {"pergunta": "Qual é o nome do animal de estimação de Cindy Lou, do filme do Grinch?", "resposta": "Max."},
    {"pergunta": "O que é o 'Mistletoe'?", "resposta": "Uma planta associada ao Natal, muitas vezes usada para beijos."},
    {"pergunta": "Quem são os personagens principais do filme 'O Estranho Mundo de Jack'?", "resposta": "Jack Skellington e Sally."},
    {"pergunta": "O que é o 'Sugar Plum Fairy'?", "resposta": "Personagem do ballet 'O Quebra-Nozes'."},
    {"pergunta": "Quem é conhecido como o 'Bom Velhinho da Coca-Cola'?", "resposta": "Papai Noel, devido às campanhas publicitárias."},
    {"pergunta": "O que são os 'Nutcrackers'?", "resposta": "Bonecos decorativos inspirados no ballet 'O Quebra-Nozes'."},
    {"pergunta": "Quem é conhecido como o 'Rei dos Presentes'?", "resposta": "Papai Noel."},
    {"pergunta": "O que é o 'Dia de Reis'?", "resposta": "Celebrado em 6 de janeiro, marcando a visita dos Três Reis Magos."},
    {"pergunta": "Quem é conhecido como o 'Papai Noel Azul'?", "resposta": "Uma versão alternativa do Papai Noel em algumas culturas."},
    {"pergunta": "O que é a 'Corrida de Papais Noéis'?", "resposta": "Eventos em que pessoas vestidas de Papai Noel correm em corridas temáticas."},
    {"pergunta": "Qual é o nome da cidade fictícia onde se passa 'Milagre na Rua 34'?", "resposta": "Nova York."},
    {"pergunta": "O que é a 'Sopa de Cebola Francesa'?", "resposta": "Um prato associado ao Natal em algumas tradições."}
]

export default data;